ENS160.Address(ENS160_I2C_ADDRESS.ADDR_0x52)
serial.redirectToUSB()
serial.writeValue("FW major", ENS160.FwMajor())
serial.writeValue("FW minor", ENS160.FwMinor())
serial.writeValue("FW build", ENS160.FwBuild())
ENS160.SetTemp(30)
ENS160.SetHumidity(80)
basic.forever(function () {
    serial.writeValue("Status", ENS160.Status())
    serial.writeValue("PartID", ENS160.PartID())
    serial.writeValue("AQI", ENS160.AQI())
    serial.writeValue("eCO2", ENS160.eCO2())
    serial.writeValue("TVOC", ENS160.TVOC())
    serial.writeValue("Humidity", ENS160.Humidity())
    serial.writeValue("Temp", ENS160.Temp())
    basic.pause(1000)
})
